name: ysolultion
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.7.0


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  bloc: ^9.0.0
  flutter_bloc: ^9.0.0
  data_connection_checker_tv: ^0.3.5-nullsafety
  dartz: ^0.10.1
  dio: ^5.8.0+1
  get_it: ^8.0.3



  
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true

